### PR TITLE
update to support symphony 2.6.x

### PR DESCRIPTION
**Pull request by jonmifsud**
More or less similar stuff I just did with ETM + Other changes to support symphony 2.6.x such as using Symphony::Author() to get the current author, and using the autoloader for the cron. I should have covered at least the basics but as a first time user of ENM I might have missed some things.

### CODE REVIEW

**Comment by michael-e** [comment]
As mentioned in [another issue](https://github.com/creativedutchmen/email_newsletter_manager/issues/62#issuecomment-70993868), there is a backwards-compatible way to introduce `Symphony::Author()`. But the `$symphony-url` param breaks compatibility anyway, so I would leave that as it is. (He, Symphony 2.6 is the way to go!)

Regarding the compatibility info: I think that `Symphony::Author()` has been introduced in 2.5, so ENM `2.0.1` should end with Symphony `2.4.x`. I suggest to skip Symphony 2.5 – I feel that it is not heavily used in production anyway. @jonmifsud: Can you change that, please?

Apart from that I tend to accept this PR, if @creativedutchmen is OK with it.

As far as I see, the PR should solve both problems in #62, correct?

**Comment by jonmifsud** [comment]
@michael-e done, should solve both issues in #62 at least I don't seem to have any issues when sending now. 

I did run into a couple of 500s but it seems totally unrelated due to logs not rotating. Every time I cleared the logs it worked just fine. That said I had quite a few notices coming up but I didn't go through them.

**Comment by michael-e** [comment]
Thanks a lot!

BTW, I posted a related issue, #67.

**Comment by michael-e** [comment]
@jonmifsud: Would you like to work on #67, or would you rather leave this to me and @creativedutchmen?

**Pull request merged**
